version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "menu-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1r40tzjgqag1y"
s3_prefix = "menu-lambda"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
